[versions]
detekt = "1.21.0"  # Note: Plugin versions must be updated in the settings.gradle.kts too
kotlin = "1.7.20"  # Note: Plugin versions must be updated in the settings.gradle.kts too

jansi = "2.4.0"
kord-extensions = "1.5.5-SNAPSHOT"
kx-ser = "1.4.1"
logging = "3.0.4"
logback = "1.4.4"
gson = "2.10"

[libraries]
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }
kx-ser = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kx-ser" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson"}
