[versions]
detekt = "1.23.5"  # Note: Plugin versions must be updated in the settings.gradle.kts too

jansi = "2.4.1"
kx-ser = "1.8.0"
logging = "7.0.3"
gson = "2.12.1"
doc-gen = "0.3.0-rc.2"
kmongo = "5.1.0"
groovy = "3.0.23"
logback = "1.5.7"
logback-groovy = "1.14.5"

[libraries]
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
logging = { module = "io.github.oshai:kotlin-logging", version.ref = "logging" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-groovy = { module = "io.github.virtualdogbert:logback-groovy-config", version.ref = "logback-groovy" }
kx-ser = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kx-ser" }
kx-ser-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kx-ser" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
doc-gen = { module="org.hyacinthbots:doc-generator", version.ref = "doc-gen" }
kmongo = { module="org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo"}
groovy = { module="org.codehaus.groovy:groovy", version.ref = "groovy" }
