[versions]
kotlin = "2.3.10"  # Note: Plugin versions must be updated in the settings.gradle.kts too

groovy = "3.0.25"
jansi = "2.4.2"
kx-ser = "1.10.0"
logback = "1.5.32"
logback-groovy = "1.14.5"
logging = "8.0.01"
kx-coroutines = "1.10.2"
kmongo = "5.5.1"
kordex-gradle = "1.9.0"
doc-gen = "0.3.0-rc.2"
gson = "2.13.2"
kordex-translation = "1.1.1"


[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
doc-gen = { module="org.hyacinthbots:doc-generator", version.ref = "doc-gen" }
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kx-ser = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kx-ser" }
kx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kx-coroutines" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-groovy = { module = "io.github.virtualdogbert:logback-groovy-config", version.ref = "logback-groovy" }
logging = { module = "io.github.oshai:kotlin-logging", version.ref = "logging" }
kmongo = { module="org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

kordex-docker = { id = "dev.kordex.gradle.docker", version.ref = "kordex-gradle" }
kordex-plugin = { id = "dev.kordex.gradle.kordex", version.ref = "kordex-gradle" }
kordex-translation = { id = "dev.kordex.gradle.i18n", version.ref = "kordex-translation" }

