/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.hyacinthbots.allium

import com.google.gson.JsonArray
import com.google.gson.JsonParser
import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.modules.extra.mappings.extMappings
import com.kotlindiscord.kord.extensions.utils.env
import me.shedaniel.linkie.utils.readText
import org.hyacinthbots.allium.extensions.About
import org.hyacinthbots.allium.extensions.EventHooks
import org.hyacinthbots.allium.extensions.Modrinth
import org.hyacinthbots.allium.extensions.PresenceUpdater
import org.hyacinthbots.allium.utils.TOKEN
import org.hyacinthbots.docgenerator.docsGenerator
import org.hyacinthbots.docgenerator.enums.CommandTypes
import org.hyacinthbots.docgenerator.enums.SupportedFileFormat
import java.util.*
import kotlin.io.path.Path

var splashes = JsonArray()
var updatemessages = JsonArray()

suspend fun main() {
    splashes = JsonParser.parseString({}.javaClass.getResource("/splashes.json")?.readText()).asJsonArray
    updatemessages = JsonParser.parseString({}.javaClass.getResource("/updatemessage.json")?.readText()).asJsonArray
    val bot = ExtensibleBot(TOKEN) {
        extensions {
            add(::EventHooks)
            add(::Modrinth)
            add(::About)
            add(::PresenceUpdater)
            extMappings {  }
        }
        i18n {
            defaultLocale = Locale.ENGLISH
        }
        docsGenerator {
            enabled = true
            environment = env("environment")
            filePath = Path("./docs/commands.md")
            fileFormat = SupportedFileFormat.MARKDOWN
            commandTypes = listOf(CommandTypes.SLASH)
        }
    }
    bot.start()
}
