/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.notjansel.sbbot

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.modules.extra.mappings.extMappings
import com.kotlindiscord.kord.extensions.utils.env
import de.notjansel.sbbot.extensions.*
import dev.kord.common.Color
import dev.kord.common.entity.Snowflake
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.util.*

val TEST_SERVER_ID = Snowflake(
    env("TEST_SERVER").toLong()  // Get the test server ID from the env vars or a .env file
)

val TEST_SERVER_CHANNEL_ID = Snowflake(
    env("TEST_CHANNEL").toLong() // Get the test channel ID from the env vars or a .env file
)

private val TOKEN = env("TOKEN")   // Get the bot' token from the env vars or a .env file
suspend fun main() {
    if (File("./logs/latest.log").exists()) {
        File("./logs/latest.log").renameTo(File("./logs/log-${File("./logs/").listFiles()?.size}"))
        withContext(Dispatchers.IO) {
            File("./logs/latest.log").createNewFile()
        }
    } else {
        withContext(Dispatchers.IO) {
            File("./logs/").mkdirs()
            File("./logs/latest.log").createNewFile()
        }
    }
    val bot = ExtensibleBot(TOKEN) {
        extensions {
            add(::Skyblock)
            add(::Startup)
            add(::Modrinth)
            add(::About)
            add(::Build)
            help {
                enableBundledExtension = true
                color {
                    Color(69420727)
                }
            }
            extMappings {  }
        }
        i18n {
            defaultLocale = Locale.ENGLISH
        }
    }
    bot.start()
}
