name: Build & Publish

on:
  push:
    branches:
      - root
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Upload artifacts (Main JAR)
        uses: actions/upload-artifact@v2
        with:
          name: Main JAR-File
          path: build/libs/*-all.jar

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          host='paulsnextcloud.ddns.net'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: Upload to Dev Server
        run: scp -i ./../private.key -P 727 ./build/libs/*-all.jar jansel@paulsnextcloud.ddns.net:/home/jansel/sbbot-beta
        shell: bash